#!/usr/bin/env python3
"""Shared narration text for the demo video — one entry per slide.
Written phonetically for TTS. Imported by both voiceover generators."""

LINES = {
 "v01": "Nature builds its strongest molecular motors as rings of identical parts. We rebuilt one as a single, addressable chain — to ask a question the ring itself hides. I'm Longfu Xu, from the Bustamante Lab at Berkeley.",
 "v02": "The phi-29 gp-sixteen motor packs DNA at nearly sixty piconewtons of force — as five identical subunits. But its real questions are per-subunit: which seat is the special, regulatory one? Is ATP fired one seat at a time, or all at once? In a ring of identical parts you can't tell. Put in a defect, and it lands at a random, unknown seat.",
 "v03": "So we make the seats addressable. Fuse the five subunits into one gene, and a mutation in copy k lands at ring seat k — every time. It's the trick that made single-chain clip-ex interpretable, twenty years ago. No one had done it for gp-sixteen. Rebuild it, to understand it.",
 "v04": "Here's the lead: c-p-two-thirty-three — one seventeen-hundred-and-fifty-residue chain. Three independent structure predictors — Bolts-two, Open-fold-three, and AlphaFold-three — all agree: five interfaces out of five. And it superimposes on the real motor — under two angstroms per subunit, all five copies landing on the native ring. The only extra density is the linker.",
 "v05": "That's predictors. Now physics. In molecular dynamics, the apo ring stays shut, the ATP-bound native pops two seams open — and our design stays closed, all five catalytic interfaces engaged, with an interface energy even tighter than native. A physics engine that never saw our metrics, agreeing anyway.",
 "v06": "But closing the ring is not enough. Drop each design into the real motor, with its DNA — and c-p-two-thirty-three's channel threads the double helix, just like native. Two rival cuts also close the ring, yet their channels are too narrow to thread DNA at all. Closing the ring is not the same as working as a motor.",
 "v07": "And here's the payoff. We install a catalytically dead subunit — E-one-nineteen-Q — at one chosen seat, or at all five. The ring stays fully closed every time. A position control seals it: remove a single arginine finger, and it disables exactly the one interface we edited — and no other. The defect goes where we chose. That is genetic addressability.",
 "v08": "One honest caveat. On gp-sixteen, the single chain is genuinely more coordinated than native — nearly one-point-eight fold. But test the same idea on clip-ex, and that advantage vanishes. So this is not a universal law of covalency — it's a property of gp-sixteen's topology. We report the null as loudly as the win.",
 "v09": "Zoom out. Across thirteen ring motors, the whole build problem collapses to one rule: if a terminus fouls the substrate channel, use circular permutation; otherwise, fuse directly. Three for three on the systems where we already know the answer. From structure alone, we can predict how to build a motor into a single chain.",
 "v10": "And we tested the framework where the answer is already known. Run blind on clip-ex, it passes the good motor six out of six — and catches the two dead-coupler mutants at zero out of six. It separates functional from broken.",
 "v11": "How? A five-level metric hierarchy that grades geometry and function — never global confidence. Plus an em-ess-ay-tiling trick that roughly doubled prediction confidence, and made a seventeen-hundred-residue ring foldable at all.",
 "v12": "What it unlocks: set the ATP pattern at chosen seats, read out the force in optical tweezers, and finally decide whether firing is sequential or concerted. That's the bridge from design to measurement.",
 "v13": "All of this ran on Claude. Claude Code orchestrated every GPU job — and a workflow of nineteen sub-agents that scored, then adversarially re-checked, every fold. That verification changed the science: it caught false negatives, and it's why the honest nulls are in this talk at all. Claude Science ran the folding campaigns. Total compute: under ten dollars.",
 "v14": "Predict the build. Rank the coupling. Design something stronger — then measure it. It's cross-checked, not yet validated in the lab, and every prediction here is a falsifiable hypothesis. A molecular motor we can both predict and measure. Thank you.",
}
